(function(g){var window=this;'use strict';var g6=function(a,b){g.S.call(this,{J:"button",Ka:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],Y:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},X:[{J:"svg",Y:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},X:[{J:"g",Y:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},X:[{J:"g",Y:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
X:[{J:"path",Y:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.K=a;this.listen("click",this.onClick,this);this.updateValue("title",g.kS(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.iS(b.Ze(),this.element))},jnb=function(a){g.S.call(this,
{J:"div",
S:"ytp-miniplayer-ui"});this.W=this.G=!1;this.player=a;this.T(a,"minimized",this.Eh);this.T(a,"onStateChange",this.Bfa);this.T(a,"documentpictureinpicturechange",this.Lba)},knb=function(a,b){g.Bp(a.player.getRootNode(),"ytp-player-minimized",b);
a.player.N("web_cairo_modern_miniplayer")&&g.Bp(a.player.getRootNode(),"ytp-modern-miniplayer",b);a.player.N("web_cairo_modern_miniplayer_inset_progress_bar")&&g.Bp(a.player.getRootNode(),"ytp-miniplayer-alternate-ui",b)},lnb=function(a){var b=a.player.qb().getPlayerSize().width,c=0,d=b;
if(a.player.N("web_cairo_modern_miniplayer")&&!a.W&&!a.player.N("web_cairo_modern_miniplayer_infobar")||a.player.N("web_cairo_modern_miniplayer_inset_progress_bar"))c=12,d=b-24;g.h5a(a.progressBar,c,d,!1);g.CZ(a.progressBar)},mnb=function(a){g.kY.call(this,a);
this.B=new g.eG(this);this.j=new jnb(this.player);this.j.hide();g.sS(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Bp(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(g6,g.S);g6.prototype.onClick=function(){this.K.gb("onExpandMiniplayer")};g.w(jnb,g.S);g.k=jnb.prototype;
g.k.show=function(){this.j=new g.op(this.I5,null,this);this.j.start();if(!this.G){this.tooltip=new g.l_(this.player,this);g.P(this,this.tooltip);g.sS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.ze=new g.LY(this.player);g.P(this,this.ze);this.progressBar=new g.BZ(this.player,this);g.P(this,this.progressBar);g.sS(this.player,this.progressBar.element,4);this.player.N("web_cairo_modern_miniplayer_infobar")&&g.xp(this.player.getRootNode(),"ytp-always-showing-infobar");this.B=new g.S({J:"div",
S:"ytp-miniplayer-scrim"});g.P(this,this.B);this.B.Ha(this.element);this.T(this.B.element,"click",this.m1);var a=new g.S({J:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},X:[g.Ux()]});g.P(this,a);a.Ha(this.B.element);this.T(a.element,"click",this.QV);a=new g6(this.player,this);g.P(this,a);a.Ha(this.B.element);this.C=new g.S({J:"div",S:"ytp-miniplayer-controls"});g.P(this,this.C);this.C.Ha(this.B.element);this.player.N("web_cairo_modern_miniplayer")||this.T(this.C.element,
"click",this.m1);var b=new g.S({J:"div",S:"ytp-miniplayer-button-container"});g.P(this,b);b.Ha(this.C.element);a=new g.S({J:"div",S:"ytp-miniplayer-play-button-container"});g.P(this,a);a.Ha(this.C.element);var c=new g.S({J:"div",S:"ytp-miniplayer-button-container"});g.P(this,c);c.Ha(this.C.element);this.Z=new g.wZ(this.player,this,!1);g.P(this,this.Z);this.Z.Ha(b.element);b=new g.vZ(this.player,this);g.P(this,b);b.Ha(a.element);this.nextButton=new g.wZ(this.player,this,!0);g.P(this,this.nextButton);
this.nextButton.Ha(c.element);this.L=this.player.N("web_cairo_modern_miniplayer")?new g.e_(this.player,this,0):new g.e_(this.player,this);g.P(this,this.L);this.L.Ha(this.B.element);this.D=new g.S({J:"div",S:"ytp-miniplayer-buttons"});g.P(this,this.D);g.sS(this.player,this.D.element,4);a=new g.S({J:"button",Ka:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},X:[g.Ux()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.QV);a=new g.S({J:"button",Ka:["ytp-miniplayer-replay-button",
"ytp-button"],Y:{"aria-label":"Close"},X:[g.$x()]});g.P(this,a);a.Ha(this.D.element);this.T(a.element,"click",this.Qca);this.player.N("web_cairo_modern_miniplayer")&&(a=new g6(this.player,this),g.P(this,a),a.Ha(this.D.element));this.T(this.player,"presentingplayerstatechange",this.J5);this.T(this.player,"appresize",this.lc);this.T(this.player,"fullscreentoggled",this.lc);this.player.N("web_cairo_modern_miniplayer")&&this.T(this.player,"onPlaylistUpdate",this.YS);this.lc();this.G=!0}this.player.getPlayerState()!==
0&&g.S.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.S.prototype.xa.call(this)};
g.k.QV=function(){this.player.N("kevlar_watch_while_v2")||this.player.stopVideo();this.player.gb("onCloseMiniplayer")};
g.k.Qca=function(){this.player.playVideo()};
g.k.m1=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.Eh=function(){knb(this,this.player.isMinimized());this.player.N("web_cairo_modern_miniplayer")&&this.YS()};
g.k.Lba=function(){knb(this,this.player.pj());this.player.N("web_cairo_modern_miniplayer")&&this.YS();g.Bp(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.pj())};
g.k.Kg=function(){this.progressBar.Uc();this.L.Uc()};
g.k.I5=function(){this.Kg();this.j&&this.j.start()};
g.k.J5=function(a){g.T(a.state,32)&&this.tooltip.hide()};
g.k.YS=function(){this.W=(this.player.isMinimized()||this.player.pj())&&!!this.player.getPlaylist();g.Bp(this.player.getRootNode(),"ytp-has-playlist-data",this.W);lnb(this)};
g.k.lc=function(){lnb(this)};
g.k.Bfa=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Ze=function(){return this.tooltip};
g.k.Xy=function(a,b,c,d,e){var f=0,h=0,l=0,m=g.Lm(a);d=b&&(g.wp(b,"ytp-prev-button")||g.wp(b,"ytp-next-button"));if(b){c=g.wp(b,"ytp-play-button");var n=g.wp(b,"ytp-miniplayer-expand-watch-page-button");d?f=l=12:c?(b=g.Jm(b,this.element),l=b.x,f=b.y-12):n&&(l=g.wp(b,"ytp-miniplayer-button-top-left"),f=g.Jm(b,this.element),b=g.Lm(b),l?(l=8,f=f.y+40):(l=f.x-m.width+b.width,f=f.y-20))}else l=c-m.width/2,h=25+(e||0);b=this.player.qb().getPlayerSize();e=f+(e||0);m=g.wg(l,0,b.width-m.width-12);e?(a.style.top=
e+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=h+"px");a.style.left=m+"px";this.player.N("web_cairo_modern_miniplayer")&&(h=g.wp(a,"ytp-preview"),a.style.visibility=d&&h&&b.height<225?"hidden":"")};g.w(mnb,g.kY);g.k=mnb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Bp(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.kY.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.On=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.jY("miniplayer",mnb);})(_yt_player);
